project_name: lucaskit

before:
  hooks:
    - go mod tidy

builds:
  - id: ultradns
    main: ./main.go
    binary: ultradns
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: sitestress
    main: ./cmd/SiteStress/main.go
    binary: sitestress
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: lucaskit
    main: ./cmd/lucaskit/main.go
    binary: lucaskit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - ultradns
      - sitestress
      - lucaskit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "lucaskit_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

